export enum DevStack {
  Unity = "Unity",
  Typescript = "Typescript",
  React = "React",
  Remix = "Remix",
  Flutter = "Flutter",
  Firebase = "Firebase",
  Nodejs = "Nodejs",
  Android = "Android",
  Javascript = "Javascript",
  Java = "Java",
  Playwright = "Playwright",
  Netlify = "Netlify",
  Nextjs = "Next.js",
  Vercel = "Vercel",
  Unreal = "Unreal Engine",
  Arduino = "Arduino",
}
